singly:
	gcc singly.c _user_input_singly.c -o main

circDoubly:
	gcc circDoubly.c _user_input_circDoubly.c -o main

doubly:
	gcc doubly.c _user_input_doubly.c -o main

circSingly:
	gcc circSingly.c _user_input_circSingly.c -o main